### ISSUE TITLE
Node don't correctly reconnet if already registered with the boostrap server

### ISSUE THREAD

**Issue by heshanpadmasiri** [KalanaDananjaya/distributed-content-search#16]
@LahiruOshara Implement this line:
https://github.com/KalanaDananjaya/distributed-content-search/blob/e55b1051e43bb5977af2f1d9cba71416398422f9/src/main/java/com/distributed/p2pFileTransfer/Network.java#L159

**Comment by ThameeraHettiwatta** [comment]
this works fine now. But it has a small delay when downloading a file

**Comment by thameera-lh** [comment]
working fine
