### ISSUE TITLE
Handle cases where no file matches the search

### ISSUE THREAD

**Issue by heshanpadmasiri** [KalanaDananjaya/distributed-content-search#18]
@KalanaDananjaya If the search result is empty show it in the terminal. Currently silently ignored.

https://github.com/KalanaDananjaya/distributed-content-search/blob/04c18ed1b74b2865f51dababa0f8eba428916440/src/main/java/com/distributed/p2pClient/Main.java#L47

**Comment by KalanaDananjaya** [comment]
Fixed with 0b94568
