### ISSUE TITLE
Change the signature of download file

### ISSUE THREAD

**Issue by heshanpadmasiri** [KalanaDananjaya/distributed-content-search#2]
https://github.com/KalanaDananjaya/distributed-content-search/blob/511c9f3218a2ac8364ef16d43dad955cf711b697/src/main/java/com/distributed/p2pFileTransfer/FileHandler.java#L31

Since paths for both normal download (= downloads by the user) (I assume this is local dir, otherwise let's add another parameter to the constructor called download dir) and the cache is already given in the constructor this public function which can be used to download files where needed is redundant. Instead, add two new protected functions one to download to the download dir (will be called when the user asks to download a file) and another to cache a file (will be called by the thread handling search requests received from other nodes), and remove this function from the protected interface. 
_I think the easiest way will be to make this function private and create two protected functions which will call this with the correct values for the destination_

**Comment by KalanaDananjaya** [comment]
Resolve with 3d7a555b568bdcc6e2925470dc0ec42283cea9a8
