### ISSUE TITLE
Change the executor service

### ISSUE THREAD

**Issue by heshanpadmasiri** [KalanaDananjaya/distributed-content-search#3]
https://github.com/KalanaDananjaya/distributed-content-search/blob/511c9f3218a2ac8364ef16d43dad955cf711b697/src/main/java/com/distributed/p2pFileTransfer/FileHandler.java#L35

It would be better if we don't create separate executor services for each function calls because it is expensive to create them. If possible move it to the constructor. _(If we do this change the single thread executor to something like fixedThreadPool (if we have a reason to control the maximum number of parallel file download threads) or cachedThreadPool)_

**Comment by KalanaDananjaya** [comment]
Resolved with 3d7a555b568bdcc6e2925470dc0ec42283cea9a8
