### ISSUE TITLE
Replace all prints with loggers

### ISSUE THREAD

**Issue by heshanpadmasiri** [KalanaDananjaya/distributed-content-search#4]
https://github.com/KalanaDananjaya/distributed-content-search/blob/511c9f3218a2ac8364ef16d43dad955cf711b697/src/main/java/com/distributed/p2pFileTransfer/FileHandler.java#L39

I think it will be better if we can replace all the print statements with loggers (nothing fancy just use the java.util.logging.Logger) so all the outputs user sees are from the client application (Thameera's part). Otherwise, when we want to change the outputs we will have to check the entire project to find where the output came from. 

_Better if you can follow the same process I have used so we can easily find from where the log came from
https://github.com/heshanpadmasiri/distributed-content-search/blob/beb3d476c0d7f2c970d3232695dcca642b355057/src/main/java/com/distributed/p2pFileTransfer/Executor.java#L25_

**Comment by KalanaDananjaya** [comment]
Resolved with 3d7a555b568bdcc6e2925470dc0ec42283cea9a8
